### ISSUE TITLE
how to set up bungeepexbridge with multiple perms databases?

### ISSUE THREAD

**Issue by alimansfield2016** [guipenedo/BungeePexBridge#10]
how does one go about configuring this to work with multiple permissions databases?
or is there a way to configure pex to make this easier?

**Comment by guipenedo** [comment]
How exactly is your pex setup?

**Comment by alimansfield2016** [comment]
I have a MySQL database, PexPermsSMP, PexPermsHub etc, one for each server. each has their own tables.

**Comment by guipenedo** [comment]
Ok. I suggest you use pex's database and tables for bungee. Simply add your bungee perms to the pex groups and configure bungeepexbridge to use that database and tables.

**Comment by alimansfield2016** [comment]
There are multiple databases though. Is there a way to set up bungeepexbridge to work with more than one database?

**Comment by guipenedo** [comment]
Why would you need multiple databases? You just need the group definitions and the associated permissions. Can you be more specific on what you want to do with multiple databases and bungeepexbridge?

**Comment by alimansfield2016** [comment]
Ok. Even if I have just one database, how do i set bungeepexbridge to read each of the sets of three tables?

**Comment by alimansfield2016** [comment]
Forgot to mention, i already have multiple servers, so they each have a database associated with them

**Comment by guipenedo** [comment]
Could you please add me on skype? Might be easier to fix this
