### ISSUE TITLE
Groups not syncing

### ISSUE THREAD

**Issue by Mikgreg** [guipenedo/BungeePexBridge#5]
Hello!

I'm not quite sure if I'm misunderstanding the point of the plugin or something is going wrong. I have permissionsex running on all of my servers and all of them are synced with a mysql database, the functionality I'm aiming to achieve is that if I set a user to the admin group in pex then it will give them the perms in the admin group in bungeecord's config as well.

You cannot do the commands you're allowed to in your given group. For example, here is the /perms output of my alt account.
![image](https://cloud.githubusercontent.com/assets/7613340/25305522/c98f14e0-2774-11e7-8421-c12500fe3f7a.png)
I cannot do any of those commands, not even /server. This is fixed when I disable the plugin.

Any help appreciated. Thank you.

**EDIT** Turns out its a problem with SEXYPEX. When using Sexypex you can't use the permissions defined in the bungeecord config even though it can list which ones you're supposed to have.

**Comment by guipenedo** [comment]
Could you clarify whether you are using sexypex or pex?

**Comment by Mikgreg** [comment]
Hey, sorry for the confusion, this issue occurs when I use Sexypex.

**Comment by guipenedo** [comment]
Sorry for the delay, could I know what versions of sexypex and pex you are using?

**Comment by Mikgreg** [comment]
Running PEX version 1.23.4
Sexypex version 1.2.1

**Comment by guipenedo** [comment]
It's been a long time. Do you still have this issue? I believe it had to do with your group setup in pex (world based groups, for example, or wrong uuids)

**Comment by guipenedo** [comment]
It's finally fixed. sorry for the delay
