### ISSUE TITLE
 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'db535233.permissions' doesn't exist

### ISSUE THREAD

**Issue by EmanYm** [guipenedo/BungeePexBridge#6]
[The error](https://pastebin.com/pmjWwkSk) - No idea why it's adding ".permissions" to the end of the database name
[BPB config](https://pastebin.com/cpv9q6Qy)
[PEX2 config](https://pastebin.com/13wCLkH3) - There is no "aliases" section in my pex config.
I did notice there is "pex_permissions" [in the database](https://i.gyazo.com/a21c841c5c119900fd9edd979e8fc64f.png)

I'm using PEX2 on my sponge servers.  The [https://i.gyazo.com/2a6e9d319565551e5c4b5ea3bcbf6447.png](review) section says it should work with PEX2.  Just wondering what I missed.

**Comment by guipenedo** [comment]
Can you change the following on bpb config:
permissions: pex_permissions
    permissionsInheritance: pex_permissions_inheritance

**Comment by guipenedo** [comment]
Actually the last one should just be pex_inheritance I believe

**Comment by EmanYm** [comment]
I thought so.  I had already changed that after I posted the issue.
Thank you for the swift response.

**Comment by EmanYm** [comment]
After taking a break and restarting bungee server I'm having a [new error](https://pastebin.com/Gy8w5HNy) now.

Edit:
I apologize for posting here.  I had not noticed your request to post bugs reports in the discussion section on spiggot

**Comment by EmanYm** [comment]
This new issue is keeping me from being able to use this on my bungee server.

**Comment by guipenedo** [comment]
After looking futher into it I've concluded that pex 2 has some changes I wasn't aware of. I'll try and update bpb asap
