### ISSUE TITLE
Update to 1.12

### ISSUE THREAD

**Issue by sadoj-kuro** [guipenedo/BungeePexBridge#8]
can you update for 1.12 i have tested but not working 

stucked in pex loaded 

> 22:27:21 [INFO] CONSOLE executed command: /end
22:27:21 [INFO] Closing listener [id: 0x792c56e5, L:/0.0.0.0:25565]
22:27:21 [INFO] Closing pending connections
22:27:21 [INFO] Disconnecting 0 connections
22:27:22 [INFO] Closing IO threads
22:27:24 [INFO] Saving reconnect locations
22:27:24 [INFO] Disabling plugins
22:27:24 [INFO] Thank you and goodbye
22:27:27 [INFO] Using OpenSSL based native cipher.
22:27:27 [INFO] Using native code compressor
22:27:27 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:eab710b:1242
22:27:27 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
22:27:27 [INFO] Epoll is working, utilising it!
22:27:27 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
22:27:27 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
22:27:27 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
22:27:27 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
22:27:27 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
22:27:27 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
22:27:27 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:eab710b:1242 by SpigotMC
22:27:27 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:eab710b:1242 by SpigotMC
22:27:27 [INFO] Loaded plugin BungeePexBridge version 1.9 by PhilipsNostrum
22:27:27 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:eab710b:1242 by SpigotMC
22:27:27 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:eab710b:1242 by SpigotMC
22:27:27 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:eab710b:1242 by SpigotMC
22:27:27 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:eab710b:1242 by SpigotMC
22:27:27 [INFO] Loaded plugin BungeeTabListPlus version 2.7.4 by CodeCrafter47
22:27:28 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:eab710b:1242 by SpigotMC
22:27:28 [INFO] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:eab710b:1242 by SpigotMC
22:27:28 [INFO] [BungeePexBridge] Permission system PEX loaded successfully!

**Comment by guipenedo** [comment]
Sorry for the delay. Do you still have this issue in the latest version?

**Comment by alimansfield2016** [comment]
It worked for me. Just took a few minutes at that point
